# These are supported funding model platforms

patreon: Rlxfly.yu
open_collective: Re7
ko_fi: Rlxfly.uwu
tidelift: nothing...
community_bridge: test
liberapay: test
issuehunt: test
otechie: XD
lfx_crowdfunding: XD
custom:  ['https://s.id/0x404']
